# Generated by Django 3.0.3 on 2020-02-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('studentId', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('collegeName', models.CharField(max_length=40)),
                ('majorName', models.CharField(max_length=40)),
                ('className', models.CharField(max_length=40)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('birthDay', models.CharField(max_length=20)),
                ('JSESSIONID', models.CharField(max_length=60)),
                ('route', models.CharField(max_length=80)),
                ('refreshTimes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
