# Generated by Django 3.0.3 on 2020-02-17 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
