# Generated by Django 3.0.3 on 2020-02-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_students_updatetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='updateTime',
            field=models.CharField(max_length=40),
        ),
    ]
